on: [push, pull_request]

jobs:
  build:
    name: ${{ github.repository }} ${{ github.repository.name }} GITHUB_REPOSITORY CI
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node_version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }} on ${{ matrix.os}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: dump variable
      run: ${{ github.repository }} ${{ github.repository.name }} GITHUB_REPOSITORY $GITHUB_REPOSITORY CI
    - name: install esy
      run: |
        npm install -g esy
    - name: Install dependencies
      run: |
        esy install
    - name: Building all in Revery
      run: |
        esy build dune build @all
    - name: Building Revery
      run: |
        esy build
    - name: Building test
      run: |
        esy build dune build test/test.exe
      env:
        CI: true
